### ISSUE TITLE
Window does not close through code

### ISSUE THREAD

**Issue by zeeshan595** [maierfelix/nvk#31]
When you use VulkanWindow.Close it does not close the window. I also tried using win.pollEvents(); after it as well and gave the same result.

![DeepinScreenshot_select-area_20190702020944](https://user-images.githubusercontent.com/6005448/60475273-78e32b00-9c6e-11e9-9bb4-ab098685b7d6.png)

**Comment by maierfelix** [comment]
Should be fixed in `0.5.9`, could you check if it's working now?

**Comment by zeeshan595** [comment]
Just updated to 0.5.9 and still the same issue. Could we expose glfwDestroyWindow?
the window stay's open for me until the process is finished.

**Comment by maierfelix** [comment]
What platform are you testing? I just ran your script above successfully on at least Windows

**Comment by zeeshan595** [comment]
Linux - Latest version of Manjaro

**Comment by zeeshan595** [comment]
Actually this might be glfw being weird. I will check to see if they have a issue for this. If i run the code below it only output's 'key pressed' once and then never triggers again. but if i remove win.close(); then it works properly and repeats every time a key is down

![DeepinScreenshot_select-area_20190702213057](https://user-images.githubusercontent.com/6005448/60544443-ae405500-9d10-11e9-86c0-22e8feb95060.png)

**Comment by zeeshan595** [comment]
Never mind, I was being an idiot. This issue is resolved and it is working properly. Apparently if you keep polling events it keep's showing the window :D
